### ISSUE TITLE
Strange events when entering an expression

### ISSUE THREAD

**Issue by saban263** [Effektgubben/Calculator#3]
I downloaded the repository sources, opened the page, enter "2*9" and get "2xx9", although I should get "2x9".
![image](https://user-images.githubusercontent.com/68595968/88053662-82a03f00-cb9f-11ea-8aab-22b2c8f5d981.png)

**Comment by saban263** [comment]
Everything breaks when I enter the multiplication sign

**Comment by TraumatizedTuna** [comment]
Thank you very much for pointing this out. I've checked and you are definitely right. I'll look into it 👍
I tried it in a somewhat older version and didn't get this weird result.

**Comment by TraumatizedTuna** [comment]
The issue should be fixed in the latest commit. Thank you very much for pointing out such an embarassing bug. Let me know if you find any other problems.
